annotations:
  category: Logging
apiVersion: v2
appVersion: v1.7.3-debian-cloudwatch-1.0
dependencies:
  - name: common
    repository: file://../common
    tags:
      - common
    version: 1.x.x
description: Chart for configure send logs to CloudWatch Logs
keywords:
  - CloudWatch
  - logging
  - fluentd
name: fluentd-cloudwatch
sources: ['https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-EKS-logs.html']
version: 1.0.6
