annotations:
  category: Monitoring
apiVersion: v2
appVersion: 1.0.0
dependencies:
  - name: common
    repository: file://../common
    tags:
      - common
    version: 1.x.x
description: Chart for health check VEriK services
keywords:
  - VEriK
  - Monitoring
  - Health check
  - Services
name: uptime-bot
sources: ['https://veriksystems.com']
version: 1.1.8