annotations:
  category: Authorization
apiVersion: v2
appVersion: 1.0.0
dependencies:
  - name: common
    repository: file://../common
    tags:
      - common
    version: 1.x.x
description: Chart to init cluster reader account
keywords:
  - rbac
  - cluster reader
name: cluster-reader
sources: ['https://kubernetes.io/docs/reference/access-authn-authz/rbac/']
version: 1.0.3
